// Lead Email Template IDs
// These strings are passed as `template` to the Email Microservice.

export const LEAD_RECEIVED             = 'LEAD_RECEIVED';
export const LEAD_ADMIN_NOTIFICATION   = 'LEAD_ADMIN_NOTIFICATION';

export const LEAD_CONTACT_REPLY        = 'LEAD_CONTACT_REPLY';
export const LEAD_FOLLOW_UP_REMINDER   = 'LEAD_FOLLOW_UP_REMINDER';
export const LEAD_STATUS_CHANGED       = 'LEAD_STATUS_CHANGED';

export const PROJECT_PROPOSAL_EMAIL    = 'PROJECT_PROPOSAL_EMAIL';
export const LEAD_PROPOSAL_ACCEPTED    = 'LEAD_PROPOSAL_ACCEPTED';
export const LEAD_ADMIN_PROPOSAL_ACCEPTED = 'LEAD_ADMIN_PROPOSAL_ACCEPTED';
export const LEAD_PROPOSAL_DECLINED_ACK   = 'LEAD_PROPOSAL_DECLINED_ACK';
export const LEAD_ADMIN_PROPOSAL_DECLINED = 'LEAD_ADMIN_PROPOSAL_DECLINED';
export const LEAD_PROPOSAL_EXPIRING    = 'LEAD_PROPOSAL_EXPIRING';
export const LEAD_PROPOSAL_EXPIRED     = 'LEAD_PROPOSAL_EXPIRED';

export const LEAD_CONTRACT_SENT        = 'LEAD_CONTRACT_SENT';
export const LEAD_CONTRACT_SIGNED      = 'LEAD_CONTRACT_SIGNED';

export const LEAD_WON_NOTIFICATION     = 'LEAD_WON_NOTIFICATION';
export const LEAD_LOST_NOTIFICATION    = 'LEAD_LOST_NOTIFICATION';
